title: Mansoor’s Docs
description: Personal site & documentation
theme: just-the-docs
url: "https://mansoorhamidzadeh.github.io"

aux_links:
  "GitHub Profile": "https://github.com/mansoorhamidzadeh"
